apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-azure-vote-front
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-azure-vote-front
    spec:
      containers:
      - name: {{ .Release.Name }}-azure-vote-front
        image: {{ .Values.IMAGE_REGISTRY }}/azure-vote-cosmos:{{ .Values.IMAGE_VERSION }}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: COSMOS_DB_ENDPOINT
          value: {{ .Values.COSMOS_DB_ENDPOINT }}
        - name: COSMOS_DB_MASTERKEY
          value: {{ .Values.COSMOS_DB_MASTERKEY }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-azure-vote-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: {{ .Release.Name }}-azure-vote-front